export default {
  SAVE_FRIEND: "SAVE_FRIEND",
  FETCH_FRIENDS: "FETCH_FRIENDS",
  FETCH_FRIENDS_REDUCER_PERSIST: "FETCH_FRIENDS_REDUCER_PERSIST",

  RAFFLE: "RAFFLE",
  FETCH_RAFFLES: "FETCH_RAFFLES",
  FETCH_RAFFLES_REDUCER_PERSIST: "FETCH_RAFFLES_REDUCER_PERSIST",
};
